version: '3'
services:
  
  apache:
    image: centos/httpd
    ports: 
      - "80:80"
    volumes:
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./apache-logs:/var/log/httpd"
      - "./simple.html:/var/www/html/index.html"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    links: 
      - apache
      - logstash
    ports:
      - "5403:5403"
    volumes:
      - "./apache-logs:/var/log/httpd"
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro" 

  logstash:
    image: logstash:6.5.4
    links:
      - elasticsearch
    volumes:
      - "./logstash.conf:/logstash.conf"
      - "./logstash_logs:/var/log/logstash"
    command: logstash -f /logstash.conf --config.reload.automatic
    ports:
      - "5959:5959"
      - "5044:5044"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    links:
      - kibana
    environment: 
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
