filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

filebeat.inputs:
- type: log
  paths:
    - /var/log/httpd/access.log
  input_type: log
  document_type: apache-access
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]


